[role="pagenumrestart"]
[[ch01_intro_what_is_chia]]
== Introduction

=== What Is Chia Blockchain?
What is a decentralized blockchain, in general?-::
Decentralized blockchain definition -

The value of a decentralized blockchain, like chia or bitcoin, is first that it is a collection of open and publicly usable protocols that anyone can connect to that can do many things that were previously unimaginable, similar to the internet itself, but all in the context of transferring value(AKA money) anywhere, nearly instantly and securely. The imagination of the partipants and the resources available to them being the main limiting factors of innovation to the system. 

But what is the value of removing central authority from money? Can't a large government or corporation create successful digital money that is just as good? First, we all in our guts know that a central authority cannot possibly move fast enough to keep pace with digital innovations, so all attempts at digital currencies become laggards quickly and their survival becomes an attempt to hang on to whatever value they once had for as long as possible. Second, and perhaps more importantly, centralized financial systems cannot foster the freedom of economy like dentralized systems can. Truly free economies drive real demand directly from the desires of the actual holders of the currency. This leads to true prices in the market which, of course, get responded to by industry driven by the profit motive. This all is reflected outwardly as a robust, nimble and virtuous economy. Centralized currencies based on forced top down economics cannot reflect true demand, prices or industries in the same virtuous way because by definition they are narrowly scoped; and are hence easily outcompeted by decentralized blockchains economies which can. 

Money is a very powerful concept in any society, but in a free society money takes on a special meaning because it is a representation of one individual's power to remain free. The potential for quality of life enhancements from one generation not using decentralized blockchains to the next using it are probably going to be as stark as the difference between being stuck in a child's body with limited rights forever or being a full adult with inalienable rights backed by an incorruptible force. 

The magic formula that decentralized blockchains have over other digitally conceived versions of money is a special mechanism called Nakamoto Consensus that incentivizes normal people to become individual peers in a trustlessly supported and used network.


Current State-::
Intended State-::
Why the great difference?

=== History of Chia
Bitcoin-based-:: Open source and community dependent like Bitcoin, but eco-friendly and utilizing advanced technologies unavailable to Satoshi Nakamoto 2008. 
Bram Cohen's reinvention of Nakamoto Consensus and technical improvements-:: Proof of Space/Time(PoST) was designed from scratch for the chia blockchain project by Bram Cohen. The main stated reason for him to do this is for less energy usage per unit of security, but all technical decisions were re-examined by Bram's team of engineers and many were upgraded significantly. In practice, many are more in line with the goals of the original cypherpunks whose enthusiasm drove bitcoin in the early days. Significant shortcomings of bitcoin usage as a currency, in terms of potential velocity of exchange and privacy aspects, are trivially implemented and resolved using the chialisp programming language. Chialisp is intended to have no potential side effects and minimal "syntactic sugar" giving it enhanced security and stability. Chialisp is a lisp-based smart coin programming language designed for Chia Blockchain and is also used in chia clone projects; and could even potentially be retrofitted for old blockchain projects like bitcoin if there was enough enthusiasm to do so. 

The gained energy efficiency of chia consensus methodology and the technical improvements of chialisp go a long way at representing the foundation for the feature improvements of chia over bitcoin and the gap should only increase over time given bitcoin's difficulty to introduce improvements. Many parties that find their way to to the chia project site these facts as main motivators.
Chia Corporation:: A company was formed around the project to drive development.

Prefarm of 21 million coins:: 

Corporate control mechanism. 

Centralization concerns.

=== Chia use, users and their stories
World Bank:: Carbon credit swap.
Non-Fungible Tokens (NFTs):: Creator, buyer, and seller. Intrinsic royalties. Offer files represent big leap forward in trustless transactions.
Commercial sale example:: Coffee shop. Alice(customer), Bob(coffee shop proprietor) and Carol(wholesale coffee bean seller).

=== Getting Started
Chia is protocol that can be accessed using a client application that speaks the protocol. A chia wallet is the most common user interface to the Chia protocol system, just like a web-browser is the most common user interface to the HTTP protocol system. There are several implementations of chia wallets, just like there are several implementations of web-browsers(e.g., Chrome, Firefox, Safari, Brave, Edge etc). And just like each has it's own niche based on their perceived attributes and deficits, chia wallets vary in quality and functionality in terms of security, speed of syncing, privacy etc. Included in the reference implementation of Chia Blockchain are two wallet configurations; the chia light wallet and chia full node wallet.

Chia Wallet::

Simplest - ?

Medium Difficulty - Chia Light Wallet. The need to sync and update.

Highest difficulty - Chia Full node

Quick Start::

Chia light wallet example.

Getting your first XCH::

Faucet.

Converting other currency to XCH at an exchange and sending to your wallet.

Get farming and join a pool. openchia.io

Finding the current XCH price online::

cryptocompare.com

Receiving XCH::

Your XCH recieve address is just a string representation of the 32-byte puzzle hash which is just a compressed version of the Chialisp language code that makes up the coins once value is sent to that address. More than one XCH recieve address can be created for each wallet. It is recommended to create a new XCH receive address each time you are asked to provide an address for sending to, so as to increase your personal security. 

Sending XCH::

XCH address, amounts and fees.

XCH is the unit of currency and XCH addresses are just string representations of the puzzle hash (32-byte representation) of the Chialisp puzzle that needs to be solved to spend the XCH denominated value of the coin. Standard wallet puzzles are the same for everyone and therefore get solved in a similar manner, but get they are secured by injecting the owners unique keys into the hashing calculation and can only be solved, and therefore spent, by using that same set of keys.

1 Trillion Mojos = 1 XCH

Fees are method of prioritizing transactions. There is technically no minimum fee, but certain custom chia clients, like HPOOL, require a fee greater than zero for transactions to be entered into their mempool. HPOOL represents a large enough percentage of Chia nodes that it sometimes causes a noticable delay for zero fee transactions to be included into a non-HPOOL block. That combined with the nearly infinitely small value of a single Mojo, representing 1 trillionth of about $45 value of a single XCH, make it so that including a one Mojo fee pr greater is always a good idea if timeliness of your transaction is a consideration.
