[role="pagenumrestart"]
[[ch01_intro_what_is_chia]]
== Introduction

=== What Is Chia Blockchain?
What is a decentralized blockchain, in general?-::
Decentralized blockchain definition - A secured, distributed database or ledger; where "ledger" is defined as a record of value (AKA money) along with timestamps. 

It's important to recognize first thing decentralized consensus mechanisms invented around 2008 by an anonymous programmer, or gorup of programmers, named Satoshi Nakamoto introduced significant slow downs in transaction processing over what is being used by the financial industry today and even going back 50 years. Yet there is significant value gained.

The value of a decentralized blockchain, like chia or bitcoin, comes first from the fact that it is a collection of open and publicly usable protocols that anyone can connect to that can do many things that were previously unimaginable, similar to the internet itself, but all in the context of transferring value(AKA money) anywhere, nearly instantly and securely. The imagination of the partipants being the main limiting factor of innovation to the system. Contrast that with today's financial system where the guidelines are enforced top down on the partipants who seem to be only there to carry ever more risk as innovation lags. 

How much of that value comes from removing a central authority? - Nearly all of it because in a centralized system <why they are bad>


A decentralized blockchain is always in practice slower than centralized because not only are the lookups slow, but the throughput of transactions is slow due to distributed consensus mechanism that is spread out amongst as many peers as possible. Not everything ledger-based benefits from utilizing a blockchain and even fewer things should use a decentralized blockchain. Only concepts demanding ultimate incorruptibility to sustain functionality should look to a decentralized blockchain as a solution, otherwise the downside is too great. 

It just so happens that the concept of money is was excellent initial application of a decentralized blockchain because, not only does it provide the ability to become a barrier incorruptibility necessary for any currency's long-term survival, but the intrinsic currency can be used as an incentive to attract a large enough number of people to partipate so that it easily becomes adequately resistant to attack. In fact, if you can convince enough individual people to accept payment in the currency that the decentralized blockchain project protocol creates in exchange for the protective power that their participation provides then the protocol can grow so strong as to resist any threat from any force outside; and perhaps most importanty from inside. This is largely why partipants gather around projects like bitcoin and chia blockchain. People with diverse, individualized incentives see that these systems are running for long enough, have long enough history of usage, and are open source so that the code can be inspected. What people are finding is that these dentralized blockchains are now essentially unstoppable; and their utility outweighs the cost of participation in some way so they join forces. 

If you don't agree philosophically that some portion of money should be on a secured, distributed ledger; a decentralized blockchain; then your partipatation in these projects is, at least temporarily, a faith-based endeavor. That is not the worst thing, in my opinion, because these ideas take time to sink in if at all and they need people to secure the projects, but hopefully as you become more accustomed to this environment you will also appreciate the logic behind their necessity in a growing centralized world economy that becomes less responsive to population needs and more about sustaining status-quo. Hopefully you will get more than monetary reward for the resouces you put into exploring decentralized blockchains, and enter the realm of participatory self-determination. Furthermore, chia blockchain makes a compelling argument for why it may be the one project in the genre of decentralized blockchains that you want to see succeed the most and, over time, impress your own personal stamp on the deepest.

Current State-::
Intended State-::
Why the great difference?

=== History of Chia
Bitcoin-based-:: Open source and community dependent like Bitcoin, but eco-friendly and utilizing advanced technologies unavailable to Satoshi Nakamoto 2008. 
Bram Cohen's reinvention of Nakamoto Consensus and technical improvements-:: Proof of Space/Time(PoST) was designed from scratch for the chia blockchain project by Bram Cohen. The main stated reason for him to do this is for less energy usage per unit of security, but all technical decisions were re-examined by Bram's team of engineers and many were upgraded significantly. In practice, many are more in line with the goals of the original cypherpunks whose enthusiasm drove bitcoin in the early days. Significant shortcomings of bitcoin usage as a currency, in terms of potential velocity of exchange and privacy aspects, are trivially implemented and resolved using the chialisp programming language. Chialisp is intended to have no potential side effects and minimal "syntactic sugar" giving it enhanced security and stability. Chialisp is a lisp-based smart coin programming language designed for Chia Blockchain and is also used in chia clone projects; and could even potentially be retrofitted for old blockchain projects like bitcoin if there was enough enthusiasm to do so. 

The gained energy efficiency of chia consensus methodology and the technical improvements of chialisp go a long way at representing the foundation for the feature improvements of chia over bitcoin and the gap should only increase over time given bitcoin's difficulty to introduce improvements. Many parties that find their way to to the chia project site these facts as main motivators.
Chia Corporation:: A company was formed around the project to drive development.

Prefarm of 21 million coins:: 

Corporate control mechanism. 

Centralization concerns.

=== Chia use, users and their stories
World Bank:: Carbon credit swap.
Non-Fungible Tokens (NFTs):: Creator, buyer, and seller. Intrinsic royalties. Offer files represent big leap forward in trustless transactions.
Commercial sale example:: Coffee shop. Alice(customer), Bob(coffee shop proprietor) and Carol(wholesale coffee bean seller).

=== Getting Started
Chia is protocol that can be accessed using a client application that speaks the protocol. A chia wallet is the most common user interface to the Chia protocol system, just like a web-browser is the most common user interface to the HTTP protocol system. There are several implementations of chia wallets, just like there are several implementations of web-browsers(e.g., Chrome, Firefox, Safari, Brave, Edge etc). And just like each has it's own niche based on their perceived attributes and deficits, chia wallets vary in quality and functionality in terms of security, speed of syncing, privacy etc. Included in the reference implementation of Chia Blockchain are two wallet configurations; the chia light wallet and chia full node wallet.

Chia Wallet::

Simplest - ?

Medium Difficulty - Chia Light Wallet. The need to sync and update.

Highest difficulty - Chia Full node

Quick Start::

Chia light wallet example.

Getting your first XCH::

Faucet.

Converting other currency to XCH at an exchange and sending to your wallet. For example, you could transfer USDC or USDT into something like https://www.coinex.com to trade for XCH. From there you can send to any XCH address including your chia full node or light wallet. At this time there is no fee pressure therefore moving around XCH is nearly frictionless.

Get farming and join a pool:: openchia.io

Finding the current XCH price online::

cryptocompare.com

Receiving XCH::

Your XCH recieve address is just a string representation of the 32-byte puzzle hash which is just a compressed version of the Chialisp language code that makes up the coins once value is sent to that address. More than one XCH recieve address can be created for each wallet. It is recommended to create a new XCH receive address each time you are asked to provide an address for sending to, so as to increase your personal security. 

Sending XCH::

XCH address, amounts and fees.

XCH is the unit of currency and XCH addresses are just string representations of the puzzle hash (32-byte representation) of the Chialisp puzzle that needs to be solved to spend the XCH denominated value of the coin. Standard wallet puzzles are the same for everyone and therefore get solved in a similar manner, but get they are secured by injecting the owners unique keys into the hashing calculation and can only be solved, and therefore spent, by using that same set of keys.

1 Trillion Mojos = 1 XCH

Fees are method of prioritizing transactions. There is technically no minimum fee, but certain custom chia clients, like HPOOL, require a fee greater than zero for transactions to be entered into their mempool. HPOOL represents a large enough percentage of Chia nodes that it sometimes causes a noticable delay for zero fee transactions to be included into a non-HPOOL block. That combined with the nearly infinitely small value of a single Mojo, representing 1 trillionth of about $45 value of a single XCH, make it so that including a one Mojo fee pr greater is always a good idea if timeliness of your transaction is a consideration.
