[role="pagenumrestart"]
[[ch01_intro_what_is_chia]]
== Introduction

=== What Is Chia Blockchain?
What is a blockchain, in general?-::
Current State-::
Intended State-::
Why the great difference?

=== History of Chia
Bitcoin-based-:: Open source and community dependent like Bitcoin, but eco-friendly and utilizing advanced technologies unavailable to Satoshi Nakamoto 2008. 
Bram Cohen's reinvention of Nakamoto Consensus and technical improvements-:: The main stated reason for him to do this is for less energy usage per unit of security, but all technical decisions were re-examined by Bram and his team of engineers and many were upgraded significantly. In practice, many are more in line with the goals of the original cypherpunks whose enthusiasm drove bitcoin in the early days. Many of the shortcomings of bitcoin, in terms of potential velocity of exchange and privacy aspects, are trivially implemented using the Chialisp Programming Language. Chialisp is a lisp-based smart coin programming language designed for Chia Blockchain, but can be used for all of it's clones. It rarely gets updated. It is intended to represent no side effects and minimal "syntactic sugar" giving it enhanced security and stability. The gained energy efficiency of chia consensus and the technical improvements of chialisp go a long way at representing the foundation for the feature improvements of chia over bitcoin and should only increase the gap over time. Many parties that find their way to to the chia project site these as main motivators.
Chia Corporation:: A company was formed around the project to drive development.

Prefarm of 21 million coins:: 

Corporate control mechanism. 

Centralization concerns.

=== Chia use, users and their stories
World Bank:: Carbon credit swap.
Non-Fungible Tokens (NFTs):: Creator, buyer, and seller. Intrinsic royalties. Offer files represent big leap forward in trustless transactions.
Commercial sale example:: Coffee shop. Alice(customer), Bob(coffee shop proprietor) and Carol(wholesale coffee bean seller).

=== Getting Started
Chia is protocol that can be accessed using a client application that speaks the protocol. A chia wallet is the most common user interface to the Chia protocol system, just like a web-browser is the most common user interface to the HTTP protocol system. There are several implementations of chia wallets, just like there are several implementations of web-browsers(e.g., Chrome, Firefox, Safari, Brave, Edge etc). And just like each has it's own niche based on their perceived attributes and deficits, chia wallets vary in quality and functionality in terms of security, speed of syncing, privacy etc. Included in the reference implementation of Chia Blockchain are two wallet configurations; the chia light wallet and chia full node wallet.

Chia Wallet::

Simplest - ?

Medium Difficulty - Chia Light Wallet. The need to sync and update.

Highest difficulty - Chia Full node

Quick Start::

Chia light wallet example.

Getting your first XCH::

Faucet.

Converting other currency to XCH at an exchange and sending to your wallet.

Get farming and join a pool. openchia.io

Finding the current XCH price online::

cryptocompare.com

Receiving XCH::

Your XCH recieve address is just a string representation of the 32-byte puzzle hash which is just a compressed version of the Chialisp language code that makes up the coins once value is sent to that address. More than one XCH recieve address can be created for each wallet. It is recommended to create a new XCH receive address each time you are asked to provide an address for sending to, so as to increase your personal security. 

Sending XCH::

XCH address, amounts and fees.

XCH addresses are just string representations of the puzzle hash 32-byte representation of the Chialisp puzzle that needs to be solved to spend the coin. Standard wallet puzzles are the same for everyone and therefore get solved in a similar manner, but get they are secured by injecting the owners unique keys into the hashing calculation and can only be solved, and therefore spent, by using that same set of keys.

1 Trillion Mojos = 1 XCH

Fees are method of prioritizing transactions. There is technically no minimum fee, but certain custom chia clients, like HPOOL, require a fee greater than zero for transactions to be entered into their mempool. HPOOL represents a large enough percentage of Chia nodes that it sometimes causes a noticable delay for zero fee transactions to be included into a non-HPOOL block. That combined with the nearly infinitely small value of a single Mojo, representing 1 trillionth of about $45 value of a single XCH, make it so that including a one Mojo fee pr greater is always a good idea if timeliness of your transaction is a consideration.
