[role="pagenumrestart"]
[[ch01_intro_what_is_chia]]
== Introduction

=== What Is Chia Blockchain?
What is a decentralized blockchain, in general?-::
Decentralized blockchain definition -

The value of a decentralized blockchain, like chia or bitcoin, is first, in that it is a collection of open and publicly usable protocols that anyone can connect to that can do a lot things that were previously unimaginable, similar to the internet itself, but all in the context of transferring value(AKA money) securely. The imagination of the partipants and the resources available being the main limiting factors of innovation. 

What is the value of removing central authority from money? First, we all in our guts know that a central authority cannot possibly move fast enough to keep pace with digital innovations, so all attempts at digital currencies have lagged and will continue to lag behind what is possible. Second, and perhaps more importantly, decentralized financial systems foster a freedom of economy which drives demand directly from those holding the currency which leads to true prices in a market which inevitably get responded to by industry supply mechanisms responding to the profit motive. This all is reflecting a robust and nimble economy; one that can outcompete other ecomonies that remain based on forced, top down economics that don't reflect true demand, prices or industries. Essentially decentralized blockchains facilitate the an updated rendition of free and open economies, but are a dramatic leap forward. The potential for quality of life enhancements are as great as the difference between being child with limited rights and being an adult with full privileges backed by an incorruptible system of enforcement. Money is a very powerful concept in any society, but takes on a special meaning in a free society because essentially it is representation of the power to remain free. 

There have been lots of attempts at digital value transfer and all have the similar attributes over analog money in that they can move at the speed of light over great distances and fractionlize to the tiniest decimel. This is great and some have been programmed them to do fancy things well beyond what a paper dollar or check can do, but all inevitably fail unless they are either backed by a strong analog based currency like the US dollar, or as in the case of bitcoin, ethereum and now chia they are decentralized blockchains. The magic formula that decentralized blockchains have over other digitally conceived versions of money is a special mechanism called Nakamoto Consensus that incentivizes normal people to becomes peers in a trustlessly supported and used the network and have the number of indivual participants serve as a protection of the network from attack while using the partipants respurces t do the validation of network transactions. 


Current State-::
Intended State-::
Why the great difference?

=== History of Chia
Bitcoin-based-:: Open source and community dependent like Bitcoin, but eco-friendly and utilizing advanced technologies unavailable to Satoshi Nakamoto 2008. 
Bram Cohen's reinvention of Nakamoto Consensus and technical improvements-:: Proof of Space/Time(PoST) was designed from scratch for the chia blockchain project by Bram Cohen. The main stated reason for him to do this is for less energy usage per unit of security, but all technical decisions were re-examined by Bram's team of engineers and many were upgraded significantly. In practice, many are more in line with the goals of the original cypherpunks whose enthusiasm drove bitcoin in the early days. Significant shortcomings of bitcoin usage as a currency, in terms of potential velocity of exchange and privacy aspects, are trivially implemented and resolved using the chialisp programming language. Chialisp is intended to have no potential side effects and minimal "syntactic sugar" giving it enhanced security and stability. Chialisp is a lisp-based smart coin programming language designed for Chia Blockchain and is also used in chia clone projects; and could even potentially be retrofitted for old blockchain projects like bitcoin if there was enough enthusiasm to do so. 

The gained energy efficiency of chia consensus methodology and the technical improvements of chialisp go a long way at representing the foundation for the feature improvements of chia over bitcoin and the gap should only increase over time given bitcoin's difficulty to introduce improvements. Many parties that find their way to to the chia project site these facts as main motivators.
Chia Corporation:: A company was formed around the project to drive development.

Prefarm of 21 million coins:: 

Corporate control mechanism. 

Centralization concerns.

=== Chia use, users and their stories
World Bank:: Carbon credit swap.
Non-Fungible Tokens (NFTs):: Creator, buyer, and seller. Intrinsic royalties. Offer files represent big leap forward in trustless transactions.
Commercial sale example:: Coffee shop. Alice(customer), Bob(coffee shop proprietor) and Carol(wholesale coffee bean seller).

=== Getting Started
Chia is protocol that can be accessed using a client application that speaks the protocol. A chia wallet is the most common user interface to the Chia protocol system, just like a web-browser is the most common user interface to the HTTP protocol system. There are several implementations of chia wallets, just like there are several implementations of web-browsers(e.g., Chrome, Firefox, Safari, Brave, Edge etc). And just like each has it's own niche based on their perceived attributes and deficits, chia wallets vary in quality and functionality in terms of security, speed of syncing, privacy etc. Included in the reference implementation of Chia Blockchain are two wallet configurations; the chia light wallet and chia full node wallet.

Chia Wallet::

Simplest - ?

Medium Difficulty - Chia Light Wallet. The need to sync and update.

Highest difficulty - Chia Full node

Quick Start::

Chia light wallet example.

Getting your first XCH::

Faucet.

Converting other currency to XCH at an exchange and sending to your wallet.

Get farming and join a pool. openchia.io

Finding the current XCH price online::

cryptocompare.com

Receiving XCH::

Your XCH recieve address is just a string representation of the 32-byte puzzle hash which is just a compressed version of the Chialisp language code that makes up the coins once value is sent to that address. More than one XCH recieve address can be created for each wallet. It is recommended to create a new XCH receive address each time you are asked to provide an address for sending to, so as to increase your personal security. 

Sending XCH::

XCH address, amounts and fees.

XCH is the unit of currency and XCH addresses are just string representations of the puzzle hash (32-byte representation) of the Chialisp puzzle that needs to be solved to spend the XCH denominated value of the coin. Standard wallet puzzles are the same for everyone and therefore get solved in a similar manner, but get they are secured by injecting the owners unique keys into the hashing calculation and can only be solved, and therefore spent, by using that same set of keys.

1 Trillion Mojos = 1 XCH

Fees are method of prioritizing transactions. There is technically no minimum fee, but certain custom chia clients, like HPOOL, require a fee greater than zero for transactions to be entered into their mempool. HPOOL represents a large enough percentage of Chia nodes that it sometimes causes a noticable delay for zero fee transactions to be included into a non-HPOOL block. That combined with the nearly infinitely small value of a single Mojo, representing 1 trillionth of about $45 value of a single XCH, make it so that including a one Mojo fee pr greater is always a good idea if timeliness of your transaction is a consideration.
