[role="pagenumrestart"]
[[ch01_intro_what_is_chia]]
== Introduction

=== What Is Chia Blockchain?
What is a decentralized blockchain, in general?-::
Decentralized blockchain definition - A secured, distributed database or ledger; where "ledger" is defined as a record of value (AKA money) along with timestamps. 

The value of a decentralized blockchain -

How much of that value comes from removing a central authority? - Nearly all of it. <Details why...> 

General blockchain value - Blocks and their system of connection become extremely difficult to duplicate as the chain becomes longer and heavier. That enhances their security and represents their upside technologically, but the downside is slow throughput of transactions due to distributed consensus mechanism that is spread out amongst as many peers as possible. A centralized blockchain is faster than decentralized, but offers very little technological value compared to a traditional database or ledger. In other words, not everything ledger-based would benefit from utilizing a blockchain, and even fewer things should use a decentralized blockchain. Only those things needing an ultimate incorruptible barrier should be attempted to use a decentralized blockchain. 

It just so happens that the human concept of money is an excellent incentive to get a large enough number of people to partipate in supporting a decentralized blockchain project and if you can convince them to accept payment in the currency that the project creates in exchange for their protective  power then the protocol system itself becomes really good at self-protecting from outsiders trying to bring it down. This is largely why partipants gather around projects like bitcoin and chia blockchain. People with diverse, individualized incentives see that these systems are running and have enough usage so that they are now essentially unstoppable; and their utility outweighs the cost of participation in some way. 

If you don't agree philosophically that some portion of money should be on a secured, distributed ledger; a decentralized blockchain; then your partipatation in these projects is, at least temporarily, a faith-based endeavor. That is not the worst thing, in my opinion, because these ideas take time to sink in if at all and they need people to secure the projects, but hopefully as you become more accustomed to this environment you will also appreciate the logic behind their necessity in a growing centralized world economy that becomes less responsive to population needs and more about sustaining status-quo. Hopefully you will get more than monetary reward for the resouces you put into exploring decentralized blockchains, and enter the realm of participatory self-determination. Furthermore, chia blockchain makes a compelling argument for why it may be the one project in the genre of decentralized blockchains that you want to see succeed the most and, over time, impress your own personal stamp on the deepest.

Current State-::
Intended State-::
Why the great difference?

=== History of Chia
Bitcoin-based-:: Open source and community dependent like Bitcoin, but eco-friendly and utilizing advanced technologies unavailable to Satoshi Nakamoto 2008. 
Bram Cohen's reinvention of Nakamoto Consensus and technical improvements-:: Proof of Space/Time(PoST) was designed from scratch for the chia blockchain project by Bram Cohen. The main stated reason for him to do this is for less energy usage per unit of security, but all technical decisions were re-examined by Bram's team of engineers and many were upgraded significantly. In practice, many are more in line with the goals of the original cypherpunks whose enthusiasm drove bitcoin in the early days. Significant shortcomings of bitcoin usage as a currency, in terms of potential velocity of exchange and privacy aspects, are trivially implemented and resolved using the chialisp programming language. Chialisp is intended to have no potential side effects and minimal "syntactic sugar" giving it enhanced security and stability. Chialisp is a lisp-based smart coin programming language designed for Chia Blockchain and is also used in chia clone projects; and could even potentially be retrofitted for old blockchain projects like bitcoin if there was enough enthusiasm to do so. 

The gained energy efficiency of chia consensus methodology and the technical improvements of chialisp go a long way at representing the foundation for the feature improvements of chia over bitcoin and the gap should only increase over time given bitcoin's difficulty to introduce improvements. Many parties that find their way to to the chia project site these facts as main motivators.
Chia Corporation:: A company was formed around the project to drive development.

Prefarm of 21 million coins:: 

Corporate control mechanism. 

Centralization concerns.

=== Chia use, users and their stories
World Bank:: Carbon credit swap.
Non-Fungible Tokens (NFTs):: Creator, buyer, and seller. Intrinsic royalties. Offer files represent big leap forward in trustless transactions.
Commercial sale example:: Coffee shop. Alice(customer), Bob(coffee shop proprietor) and Carol(wholesale coffee bean seller).

=== Getting Started
Chia is protocol that can be accessed using a client application that speaks the protocol. A chia wallet is the most common user interface to the Chia protocol system, just like a web-browser is the most common user interface to the HTTP protocol system. There are several implementations of chia wallets, just like there are several implementations of web-browsers(e.g., Chrome, Firefox, Safari, Brave, Edge etc). And just like each has it's own niche based on their perceived attributes and deficits, chia wallets vary in quality and functionality in terms of security, speed of syncing, privacy etc. Included in the reference implementation of Chia Blockchain are two wallet configurations; the chia light wallet and chia full node wallet.

Chia Wallet::

Simplest - ?

Medium Difficulty - Chia Light Wallet. The need to sync and update.

Highest difficulty - Chia Full node

Quick Start::

Chia light wallet example.

Getting your first XCH::

Faucet.

Converting other currency to XCH at an exchange and sending to your wallet.

Get farming and join a pool. openchia.io

Finding the current XCH price online::

cryptocompare.com

Receiving XCH::

Your XCH recieve address is just a string representation of the 32-byte puzzle hash which is just a compressed version of the Chialisp language code that makes up the coins once value is sent to that address. More than one XCH recieve address can be created for each wallet. It is recommended to create a new XCH receive address each time you are asked to provide an address for sending to, so as to increase your personal security. 

Sending XCH::

XCH address, amounts and fees.

XCH is the unit of currency and XCH addresses are just string representations of the puzzle hash (32-byte representation) of the Chialisp puzzle that needs to be solved to spend the XCH denominated value of the coin. Standard wallet puzzles are the same for everyone and therefore get solved in a similar manner, but get they are secured by injecting the owners unique keys into the hashing calculation and can only be solved, and therefore spent, by using that same set of keys.

1 Trillion Mojos = 1 XCH

Fees are method of prioritizing transactions. There is technically no minimum fee, but certain custom chia clients, like HPOOL, require a fee greater than zero for transactions to be entered into their mempool. HPOOL represents a large enough percentage of Chia nodes that it sometimes causes a noticable delay for zero fee transactions to be included into a non-HPOOL block. That combined with the nearly infinitely small value of a single Mojo, representing 1 trillionth of about $45 value of a single XCH, make it so that including a one Mojo fee pr greater is always a good idea if timeliness of your transaction is a consideration.
