== How Chia Works
The chia system, unlike traditional banking and payment systems, and much like the bitcoin system, is based on decentralized trust. Instead of a central trusted authority, like The US Federal Reserve System, in chia (and bitcoin), trust is achieved emergently from the interactions of different participants in the chia protocol system. In this chapter we will examine the chia system and it's moving parts from a high-level perspective in order to set the parameters of what chia blockchain is and, perhaps more importantly, is not. From this attitude hopefully it will become clearer to the reader what is realistically possible in this new frontier in the near term. 

By examining a single transaction in it's most general terms, but all the way through, the reader will understand the point where it becomes trusted and accepted by the chia mechanism of distributed consensus and is finally recorded to the blockchain, the distributed ledger of all transactions, and after a certain period of time becomes what some people consider part of the growing set of incontrovertible digital truth. Chia, by way of it's robust programming lanaguage and inherent auditability offers sufficiently more detail than bitcoin. What this means is that, despite chia being a younger project and having less time for the weight of digital truth to accumulate, chia potentially accumulates weight faster than bitcoin and depending on it's uptake could catch up and surpass bitcoin over time as the best digital reference for what happened in these early digital money epochs. Subsequent chapters will delve deeper into the technology behind transactions, the network, and chia farming in adequate depth, but for now we survey the landscape so as to facilitate thoughts of chia component relationships and form the most important initial discussions.

== Basic Transactions, Blocks, Farming, Emissions Schedule and General Blockchain Principles

== Transactions
Inputs-::
Outputs-::
Coin Lineage-::
Parent ID

== Blocks

== Farming

== Emissions Schedule

== General Blockchain Principles
