== How Chia Works
The chia system, unlike traditional banking and payment systems, and much like the bitcoin system, is based on decentralized trust. Instead of a central trusted authority, like The United States Federal Reserve System(The Fed), in chia and in bitcoin, trust is achieved emergently from the interactions of different participants in the chia protocol system. In this chapter, we will examine the chia system and it's moving parts from a high-level perspective in order to set the parameters of what chia blockchain is and, perhaps more importantly, is not. From this attitude hopefully it will become clearer to the reader what is realistically possible in this new frontier in the near term. 

By examining a single transaction in it's most general terms, but all the way through, the reader will understand the point where it becomes trusted and accepted by the chia mechanism of distributed consensus and is finally recorded to the blockchain, the distributed ledger of all transactions, and after a certain period of time becomes part of what some consider a set of digital truth. 

Chia, by way of it's robust chialisp programming lanaguage and inherent ease of auditability, offers sufficiently more detail to the publicly observable truth set that is emerging; much moreso than bitcoin can with it's limited scripting functionality. Therefore, despite chia being the younger project to bitcoin by over a decade and therefore having less time for the weight of it's transactions to accumulate, it potentially gets heavier much faster depending on the nature of it's uptake. Looking back years from now, chia potentially could have caught up and surpassed bitcoin as representing the most difficult to duplicate decentralized blockchain history and therefore becoming the best digital reference for all but the most nascent digital money histories, which of course already belong to bitcoin and to a certain extent other blockchains projects like Ethereum. There is no reason this cannot happen, but it all depends on a community forming around the tools that already exist and helping the porject by giving feedback regarding new tools as they emerge.

Subsequent chapters will delve deeper into the technology behind chia transactions, the network, and farming in adequate depth, but for now we survey the landscape so as to facilitate initial thoughts of the relationships between chia components and form the initial discussions that will undoubtably occur over and over in the heads, even if not outwardly, of nearly every newcomer for awhile.

== Basic Transactions, Blocks, Farming, Emissions Schedule and General Blockchain Principles

== Transactions
Inputs-::
Outputs-::
Coin Lineage-::
Parent ID

== Blocks

== Farming

== Emissions Schedule

== General Blockchain Principles
