== How Chia Works
The chia system, unlike traditional banking and payment systems, and much like the bitcoin system, is based on decentralized trust. Instead of a central trusted authority, like The US Federal Reserve System, in chia (and bitcoin), trust is achieved emergently from the interactions of different participants in the chia protocol system. In this chapter we will examine the chia system and it's moving parts from a high-level perspective in order to set the parameters of what chia blockchain is and, perhaps more importantly, is not. From this attitude hopefully it will become clearer to the reader what is realistically possible in this new frontier in the near term. 

By examining a single transaction in it's most general terms, but all the way through, the reader will understand the point where it becomes trusted and accepted by the chia mechanism of distributed consensus and is finally recorded to the blockchain, the distributed ledger of all transactions, and after a certain period of time becomes part of what some consider a set of digital truth. Chia, by way of it's robust programming lanaguage and inherent auditability, offers sufficiently more detail to the truth set than bitcoin. Therefore, despite chia being a younger project than bitcoin having less time for the weight of it's transactions to accumulate, chia potentially gets heavier faster depending on the nature of it's uptake. It's not unfathomeable that chia could catch up and surpass bitcoin over a short time as the most difficult decentralized blockchain to duplicate and therefore best digital reference for these early digital money histories. Subsequent chapters will delve deeper into the technology behind chia transactions, the network, and farming in adequate depth, but for now we survey the landscape so as to facilitate initial thoughts of the relationships between chia components and form the initial discussions.

== Basic Transactions, Blocks, Farming, Emissions Schedule and General Blockchain Principles

== Transactions
Inputs-::
Outputs-::
Coin Lineage-::
Parent ID

== Blocks

== Farming

== Emissions Schedule

== General Blockchain Principles
