== How Chia Works
The chia system, unlike traditional banking and payment systems, and much like the bitcoin system, is based on decentralized trust. Instead of a central trusted authority, like The United States Federal Reserve System(The Fed), in chia, trust is achieved emergently from the interactions of different participants in the chia protocol system. In this chapter, we will examine the chia system and it's moving parts from a high-level perspective in order to set the parameters of what chia blockchain is and, perhaps more importantly, is not. From this attitude hopefully it will become clearer to the reader what is realistically possible in this new frontier in the near term. 

By examining a single transaction in it's most general terms, but all the way through, the reader will understand the point where it becomes trusted and accepted by the chia mechanism of distributed consensus and is finally recorded to the blockchain, the distributed ledger of all transactions, and after a certain period of time becomes part of what some consider a set of digital truth. 

Chia, by way of it's robust chialisp programming lanaguage and inherent ease of auditability, offers sufficiently more detail to the publicly observable truth set that is emerging; much moreso than bitcoin can with it's limited scripting functionality. Therefore, despite chia being the younger project to bitcoin by over a decade and therefore having less time for the weight of it's transactions to accumulate, potentially grows heavier much faster. It is all dependent on the speed and nature of it's uptake. 

In other words, looking back on blockchain history years from now, chia potentially could have caught up and surpassed bitcoin as representing the most difficult to duplicate decentralized blockchain history soon from today. Once that happens chia would become the best digital reference for all but the most nascent digital money histories, which of course already belong to bitcoin and to a certain extent other blockchains projects like Ethereum. There is no reason this cannot happen and that chia could not hold onto a leading position for a very long time based on it's technological edge and goverence forethought, but it all depends on a growing community forming around the tools that already exist and helping by giving freely it's feedback about new tools as they emerge. Chia corporate and their potential large customers are important for chia blockchain's success, but there is no imaginable way that they are able to stay incentivized to test and form the proficiencies necessary to maintain such a large project ad infinitum without vast numbers of chia farmers, smart coin programmers and auditors, and a whole array of other niche particpants; all incentivized in different ways.

Subsequent chapters will delve deeper into the technology behind chia transactions, the network, and farming in adequate depth, but for now we survey the landscape so as to facilitate initial thoughts of the relationships between chia components and form the initial discussions that will undoubtably occur over and over in the heads, even if not outwardly, of nearly every newcomer to chia blockchain regardless of where they see themsleves going in the community. This will be the state for some time in my opinion.

== Basic Transactions, Blocks, Farming, Emissions Schedule and General Blockchain Principles

== Transactions
Inputs-::
Outputs-::
Coin Lineage-::
Parent ID

== Blocks

== Farming

== Emissions Schedule

== General Blockchain Principles
