== How Chia Works
The chia system, unlike traditional banking and payment systems (and like the bitcoin system), is based on decentralized trust. Instead of a central trusted authority, like The US Federal Reserve System, in chia (and bitcoin), trust is achieved as an emergent property from the interactions of different participants in the chia protocol system. In this chapter we will examine the system from a high-level perspective in order to set the parameters of what chia blockchain is and, perhaps more importantly, is not. From this attitude hopefully it will be clearer what is realistically possible in this new frontier. By examining a single transaction in general terms, but all the way through, the reader will understand the point where it becomes trusted and accepted by the chia mechanism of distributed consensus and is finally recorded to the blockchain, the distributed ledger of all transactions, and after a certain period of time becomes incontrovertible digital truth with sufficiently more detail than bitcoin, as facilitated by the unique attributes of the chia blockchain. Subsequent chapters will delve into the technology behind transactions, the network, and farming in adequate depth. For now we survey the landscape so as to facilitate component relationship thoughts and initial discussions.

== Basic Transactions, Blocks, Farming, Emissions Schedule and General Blockchain Principles

== Transactions
Inputs-::
Outputs-::
Coin Lineage-::
Parent ID

== Blocks

== Farming

== Emissions Schedule

== General Blockchain Principles
