== Keys and Addresses

== Introductionn to cryptography on Chia
Private -> Public Key pairing concepts-::
test

== Basics of BLS signatures

== Puzzles, Puzzle Hashes and XCH addresses
Puzzles::

Puzzle Hashes::
A puzzle hash is simply a puzzle run as a solution through sha256tree as a puzzle. You can easily get the puzzle hash for any puzzle by using the command `cdv clsp <something something>` with the output of <puzzlehash> being your new puzzlehash. Furthermore, you can also verify the output manually using chialisp and clvm only. For example, if again the puzzle is `<puzzle>` you can run it as solution for sha256tree as a puzzle and get the same result. `brun '(a (q 2 6 (c 2 (c 5 ()))) (c (q 1 2 (i (l 5) (q 11 (q . 2) (a 6 (c 2 (c 9 ()))) (a 6 (c 2 (c 13 ())))) (q 11 (q . 1) 5)) 1) 1))'  '(<puzzle>)'` with the output of <puzzlehash>. The brun command can be run with the verbose flag `-v` to see step by step how sha256tree hashes the leaves of the original puzzle working it's way up binary tree to the root until outputting a final 32-byte puzzle hash that uniquely represents the original puzzle in a standard compressed format.

XCH addresses::
To convert a puzzle hash to an XCH address, which is just a string representation of the same thing, it is a beautifully simple command `cdv encode puzzle_hash`.

== Advanced Concepts
Custody solution using Chia::

"Sniffed Keys" - someone else knows your private key, but you don't know it.

"Stolen? Keys" - someone else knows your private key and you no longer know it.
